### ISSUE TITLE
SkipCertificateCheck should be sticky

### ISSUE THREAD

**Issue by matttrawicki** [jci-metasys/powershell-metasysrestclient#38]
It would be nice if this flag was used to connect that it is automatic for the session.

**Comment by michaelgwelch** [comment]
I'm a little torn on this one. While I myself have had to suffer thru a session with a test site (that I didn't own) that didn't have a trusted cert, I don't want to make it too easy for users to work around this security issue. 

I guess I could make it required on every use of `cma` and once the session is established remember. At least every time you initiate a session you'd need to specify the flag as a reminder that "this is insecure".

**Comment by michaelgwelch** [comment]
Ok, turns out I already implemented a variation of this.

1. `Connect-MetasysAccount` (`cma`) requires you to pass `-SkipCertificateCheck` every time you call it with a server that has invalid or untrusted cert.
2. `Invoke-MetasysMethod` (`imm`) allows you to forego passing `-SkipCertificateCheck` on every invocation by setting the env variable `$env:METASYS_SKIP_CHECK_NOT_SECURE`.

   So in your current session you can type
   
   ```push
   $env:METASYS_SKIP_CHECK_NOT_SECURE = $true
   ```

   Then you can call `imm` without `-SkipCertificateCheck`

**Comment by michaelgwelch** [comment]
As of the newer releases this flag is "sticky". If you connect with this flag specified, then the future calls to `imm` will use the same value. As always care should be taken when ignoring cert errors.
